name = "only-two-morphic-numbers"
defaultTargets = ["PdtMorphic", "Challenge", "Solution", "PdtFamilyBoundaries"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "fabf563a7c95a166b8d7b6efca11c8b4dc9d911f"

[[lean_lib]]
name = "PdtMorphic"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"

[[lean_lib]]
name = "PdtFamilyBoundaries"
